name: 'Autoland Pull Request'
description: 'Merge PRs automatically when their depending commits or PRs have been merged into other repositories'
author: 'xarantolus'

inputs:
  merge-method:
    description: "How the merge should be performed. Must be 'merge', 'squash' or 'rebase'. See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github"
    required: false
    default: merge
  users:
    description: "Which types of users are allowed to create `autoland after` comments. See https://docs.github.com/en/graphql/reference/enums#commentauthorassociation"
    required: false
    default: owner, collaborator, member

env:
  GITHUB_TOKEN: "As provided by Github Actions"

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: git-pull-request
  color: green
