name: 'Autoland'
description: 'Automatically merge PRs when another repository merges a PR or commit'
author: 'xarantolus'

inputs:
  merge-method:
    description: 'How the merge should be performed. Must be 'merge', 'squash' or 'rebase'. See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github'
    required: false
    default: merge

env:
  "GITHUB_TOKEN": "As provided by Github Actions"

runs:
  using: 'node12'
  main: 'dist/index.js'
